sudo: required
services:
    - docker
    
before_install:
    - docker build -t anandpoddar/docker-react -f Dockerfile.dev .
    
script:
    - docker run anandpoddar/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-recat"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-020501965984"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    